namespace TextToSpeechApp
{
    public class Dialogues
    {
        static string boyVoice = "Microsoft David Desktop";
        static string girlVoice = "Microsoft Zira Desktop";

        static string title = "HobbiesandPersonalProjects";

        public static List<Tuple<string, string>> ConversationList = new List<Tuple<string, string>>()
        {
            Tuple.Create(boyVoice, "Hobbies and Personal Projects"),
            Tuple.Create(boyVoice, "Hey, how have you been?"),
            Tuple.Create(girlVoice, "I’m doing well! Been keeping busy with work and some personal projects."),
            Tuple.Create(boyVoice, "Sounds good! What kind of personal projects are you working on?"),
            Tuple.Create(girlVoice, "I’ve been learning photography. I’ve always wanted to get better at it."),
            Tuple.Create(boyVoice, "That’s awesome! Have you gone on any photo walks yet?"),
            Tuple.Create(girlVoice, "Yes, actually! I went to the park last weekend to take some nature shots."),
            Tuple.Create(boyVoice, "Nice! I’ve heard natural light makes a huge difference. How did it go?"),
            Tuple.Create(girlVoice, "It went pretty well. Some of the shots turned out great! Still learning, though."),
            Tuple.Create(boyVoice, "That’s the fun part, right? Getting better over time."),
            Tuple.Create(girlVoice, "Exactly! What about you? Any new hobbies or projects?"),
            Tuple.Create(boyVoice, "I’ve been trying to get back into painting. Haven’t picked up a brush in years."),
            Tuple.Create(girlVoice, "That’s interesting! What kind of paintings do you do?"),
            Tuple.Create(boyVoice, "I mostly enjoy landscapes. I love how you can capture the essence of a place."),
            Tuple.Create(girlVoice, "Landscapes sound peaceful. Do you paint from real life or use references?"),
            Tuple.Create(boyVoice, "Both. Sometimes I paint from photos, other times, I just go outside and try to capture what I see."),
            Tuple.Create(girlVoice, "I admire that. There’s something special about painting directly from nature."),
            Tuple.Create(boyVoice, "Yeah, it’s definitely a different experience. You can almost feel the atmosphere."),
            Tuple.Create(girlVoice, "Speaking of nature, have you been on any trips lately?"),
            Tuple.Create(boyVoice, "Actually, yes! I went on a weekend getaway to the mountains."),
            Tuple.Create(girlVoice, "That sounds amazing! How was the trip?"),
            Tuple.Create(boyVoice, "It was incredible. The air up there was so fresh, and the views were breathtaking."),
            Tuple.Create(girlVoice, "I bet the mountain views were beautiful. Did you hike or just relax?"),
            Tuple.Create(boyVoice, "I did both. I went on a couple of short hikes, and then just relaxed by the lake."),
            Tuple.Create(girlVoice, "That sounds perfect. It’s so important to take a break from the daily grind."),
            Tuple.Create(boyVoice, "I agree. Nature really helps me clear my mind."),
            Tuple.Create(girlVoice, "I feel the same way. Being outside just makes everything feel more peaceful."),
            Tuple.Create(boyVoice, "Do you have any dream travel destinations?"),
            Tuple.Create(girlVoice, "Oh, definitely! I’d love to visit Japan someday. The culture, food, and scenery are all so fascinating."),
            Tuple.Create(boyVoice, "Japan is high on my list too. I’d love to see Kyoto’s temples and cherry blossoms."),
            Tuple.Create(girlVoice, "That would be amazing! I also want to visit the countryside. I’ve heard it’s so tranquil."),
            Tuple.Create(boyVoice, "I’ve read that too. It’s like stepping into a different world. So peaceful and beautiful."),
            Tuple.Create(girlVoice, "Another place I’ve been thinking about is Italy. The history and architecture there are just stunning."),
            Tuple.Create(boyVoice, "Italy is definitely on my bucket list. Rome, Florence, Venice... There’s so much to see!"),
            Tuple.Create(girlVoice, "I know! And the food! I can already imagine myself eating pizza in Naples."),
            Tuple.Create(boyVoice, "Ha! That sounds like heaven. I’d love to have authentic Italian pizza."),
            Tuple.Create(girlVoice, "Speaking of food, what’s your favorite cuisine?"),
            Tuple.Create(boyVoice, "I’m a huge fan of Asian cuisine. Chinese, Japanese, Thai… I love all of it."),
            Tuple.Create(girlVoice, "Same here! I can’t get enough of sushi and Thai curry."),
            Tuple.Create(boyVoice, "Yes! Sushi is one of my all-time favorites. I could eat it every day."),
            Tuple.Create(girlVoice, "I love sushi too. Have you ever tried making it at home?"),
            Tuple.Create(boyVoice, "I have! It’s surprisingly easy. I made sushi rolls with avocado, cucumber, and salmon."),
            Tuple.Create(girlVoice, "That sounds delicious! I should try it. I’ve been thinking about making homemade ramen too."),
            Tuple.Create(boyVoice, "Homemade ramen is amazing! The broth takes a while, but it’s totally worth it."),
            Tuple.Create(girlVoice, "I’ve seen so many recipes online. I’ll definitely give it a shot sometime."),
            Tuple.Create(boyVoice, "You should! It’s a lot of fun to make, and it tastes way better than store-bought."),
            Tuple.Create(girlVoice, "I’ll have to try it! Do you like cooking in general?"),
            Tuple.Create(boyVoice, "Yeah, I love cooking. It’s one of my favorite ways to relax and unwind."),
            Tuple.Create(girlVoice, "Cooking is such a therapeutic activity. What’s your go-to meal to cook?"),
            Tuple.Create(boyVoice, "It’s hard to pick just one, but I love making pasta dishes—especially with a homemade sauce."),
            Tuple.Create(girlVoice, "That sounds so good! I love making pasta too, especially with lots of cheese."),
            Tuple.Create(boyVoice, "Cheese makes everything better! Have you tried making lasagna?"),
            Tuple.Create(girlVoice, "Yes! I made a vegetarian lasagna once, and it turned out great."),
            Tuple.Create(boyVoice, "That sounds delicious. I’ve never tried vegetarian lasagna, but I’m sure it’s amazing."),
            Tuple.Create(girlVoice, "It really is! The layers of roasted vegetables and cheese make it so hearty."),
            Tuple.Create(boyVoice, "I’ll have to try making it next time. Speaking of which, have you been watching any good shows lately?"),
            Tuple.Create(girlVoice, "I’ve been binge-watching a lot of crime dramas. There’s something so gripping about them."),
            Tuple.Create(boyVoice, "I totally get that. I’ve been watching a few detective shows myself."),
            Tuple.Create(girlVoice, "Which ones are you watching?"),
            Tuple.Create(boyVoice, "I’m watching *Sherlock* again. Benedict Cumberbatch is brilliant in it."),
            Tuple.Create(girlVoice, "I love *Sherlock*! The way the mysteries unfold is so clever."),
            Tuple.Create(boyVoice, "Yes! And the chemistry between Sherlock and Watson is so fun to watch."),
            Tuple.Create(girlVoice, "It really is. Have you seen *Mindhunter*? It’s another great crime series."),
            Tuple.Create(boyVoice, "I have! It’s chilling how well they capture the psychology of the criminals."),
            Tuple.Create(girlVoice, "Exactly! The show dives so deep into the psychology of both the investigators and the criminals."),
            Tuple.Create(boyVoice, "It’s a masterpiece. I can’t wait for the next season."),
            Tuple.Create(girlVoice, "Same here! I hope they release it soon."),
            Tuple.Create(boyVoice, "By the way, have you read any good books lately?"),
            Tuple.Create(girlVoice, "Yes, I’ve been reading *The Silent Patient* by Alex Michaelides. It’s so suspenseful."),
            Tuple.Create(boyVoice, "I’ve heard of that one! I’ve been meaning to read it. Is it as good as they say?"),
            Tuple.Create(girlVoice, "It’s amazing! It keeps you guessing until the very end."),
            Tuple.Create(boyVoice, "Sounds like a must-read. I’ll have to add it to my list."),
            Tuple.Create(girlVoice, "You should! What about you? Any books you’ve been reading?"),
            Tuple.Create(boyVoice, "I’m currently reading *Sapiens: A Brief History of Humankind*. It’s fascinating."),
            Tuple.Create(girlVoice, "I’ve heard that’s a great read! It sounds like a deep dive into history."),
            Tuple.Create(boyVoice, "It really is. The way it explores the evolution of human beings is mind-blowing."),
            Tuple.Create(girlVoice, "That’s so interesting. I’ll have to check it out after *The Silent Patient*."),
            Tuple.Create(boyVoice, "For sure! I think you’d enjoy it."),
            Tuple.Create(girlVoice, "I’ll let you know how I like it when I finish."),
            Tuple.Create(boyVoice, "I’d love to hear your thoughts on it. It’s one of those books that leaves you thinking for a while."),
            Tuple.Create(girlVoice, "Sounds like it! I’ll definitely dive into it soon."),
            Tuple.Create(boyVoice, "Great! Let’s catch up again soon, yeah?"),
            Tuple.Create(girlVoice, "Definitely! Let’s chat again soon."),
        };
    }
}
